### ISSUE TITLE
Flapjack 1.0 - release checklist

### ISSUE THREAD

**Issue by auxesis** [flapjack/flapjack#476]
- [x] Email Flapjack mailing list about deprecating old API
- [x] Review and merge @ali-graham's PR for the JSONAPI branch
- [x] Review and merge @ali-graham's PR for the JSONAPI flapjack-diner branch
- [x] Release flapjack 0.8.11 
- [x] Release flapjack-diner 1.0.0-rc1
- [x] Fix UI bugs with the `/edit_contacts` interface
- [x] @jessereynolds to cut a 0.9.0
- [x] @jessereynolds to create a 0.9 maintenance branch off master
- [x] @jessereynolds to release new 0.9 build with updated OpenSSL
- [x] @jessereynolds to announce 0.9.x release, explain what will happen for 1.0 release
- [x] @ali-graham to strip out old API
- [x] @ali-graham + @jessereynolds to GLI the CLI 
- [x] Release 1.0.0-rc1
- [x] @Hobbsee to merge slate + flapjack.wiki + gh-pages branch into flapjack.io repo
- [x] @Hobbsee to split documentation for 0.9 + 1.x releases
- [x] @Hobbsee to update 1.x documentation
- [x] @jessereynolds to build 1.0rc2 deb
- [x] @jessereynolds to build 0.9.3 deb
- [x] @jessereynolds to build 1.0rc3 deb
- [x] @ali-graham to add tasks + code to reparent entity data (JR reviewing)
- [x] @jessereynolds to fix fatal web ui bugs
- [x] ? to test jabber and jsonapi interfaces post entity rework
- [x] @Hobbsee to document how to promote a package from experimental to main. 
- [x] Release 1.0.0 of flapjack and flapjack-diner
