### ISSUE TITLE
Monitorama PDX checklist

### ISSUE THREAD

**Issue by auxesis** [flapjack/flapjack#477]
- [ ] Prepare a built vagrant-flapjack environment
- [ ] Copy prepared vagrant-flapjack environment to all of the USB sticks
- [ ] Host the vagrant-flapjack environment on bit torrent
- [ ] vagrant-flapjack tested on recent versions of vagrant and virtualbox (and vmware?)
- [x] Run through the workshop a few times in full
